apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Commont Tekton functionality.
bases:
  - ../../../base/03-cicd/02-custom-tasks
  - ../../../base/03-cicd/04-pipeline-trigger

# Nexus secret (username and password).
resources:
  - 01-nexus-secret.yaml
  - 02-pipeline-serviceaccount.yaml

# Generator options.
generatorOptions:
  labels:
    app: maven-settings
  disableNameSuffixHash: true

# Create a ConfigMap from custom settings.xml file.
configMapGenerator:
  - name: maven-settings-cm
    files:
      - settings.xml