apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-gameoflife

resources:
  - 01-namespace.yaml
  - 02-cicd-role-bindings.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cicd-image-puller
    path: 03-cicd-role-binding-patch.yaml