apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gameoflife-cicd

bases:
  - 01-tools
  - 02-decisions
  - 03-supervisor
  - 04-web-ui

resources:
  - 01-namespace.yaml
  - 02-cicd-role-bindings.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cicd-image-puller
    path: 03-cicd-role-binding-patch.yaml