apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/pittar-gameoflife/web-ui
  labels:
    app: web-ui
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: openjdk-11-el7
  name: web-ui
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: web-ui:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/pittar-gameoflife/web-ui
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-11-el7
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
