kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: supervisor-build-and-rollout-run-
spec:
  pipelineRef:
    name: build-and-rollout
  params:
    - name: "git-url"
      value: "https://github.com/pittar-gameoflife/supervisor.git"
    - name: "git-revision"
      value: "master"
    - name: "app-name"
      value: "supervisor"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace
