apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventLister: build-trigger
  name: build-trigger
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-build-trigger
    weight: 100
