apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - type: "Container"
      max:
        cpu: "1" 
        memory: "1Gi" 
      min:
        cpu: "100m" 
        memory: "256Mi" 
      default:
        cpu: "250m" 
        memory: "256Mi" 
      defaultRequest:
        cpu: "250m" 
        memory: "256Mi" 