apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: web-ui
    app.kubernetes.io/component: web-ui
    app.kubernetes.io/instance: web-ui
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: gameoflife
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  name: web-ui
spec:
  lookupPolicy:
    local: false
