apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: supervisor-trigger
  template:
     name: supervisor-trigger