apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-rollout
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: app-name
    type: string
    description: name of the deployment to be patched
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: mvn-build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - fetch-repository 
    params:
      - name: GOALS
        value: ["clean", "package", "-DskipTests"]
    workspaces:
      - name: source
        workspace: shared-workspace
      - name: maven-settings
        workspace: shared-workspace
  - name: s2i-build
    taskRef:
      name: oc-binary-build
      kind: Task
    runAfter:
      - mvn-build 
    params:
      - name: build-name
        value: "$(params.app-name)"
      - name: binary-relative-path
        value: "/target/app.jar"
    workspaces:
      - name: build-workspace
        workspace: shared-workspace
  - name: rollout-dev
    taskRef:
      name: oc-rollout-restart
      kind: Task
    runAfter:
      - s2i-build
    params:
      - name: app-name
        value: "$(params.app-name)"
      - name: namespace
        value: "gameoflife"

