kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: decisions-build-run-
spec:
  pipelineRef:
    name: decisions-build-and-rollout
  params:
    - name: "git-url"
      value: "https://github.com/pittar-gameoflife/decisions.git"
    - name: "git-revision"
      value: "master"
    - name: app-name
      value: "decisions"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace
