kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: oc-binary-build
spec:
  workspaces:
    - name: build-workspace
      description: Build workspace.
  params:
    - name: BUILD_NAME
      type: string
    - name: BINARY_RELATIVE_PATH
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.build-workspace.path)
      script: |
        #!/usr/bin/env bash
        echo "Workspace includes:"
        ls -la .
        echo "List target contents:"
        ls -l $(workspaces.build-workspace.path)/target
        oc start-build $(params.BUILD_NAME) --from-file=$(workspaces.build-workspace.path)$(params.BINARY_RELATIVE_PATH) --follow