kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: oc-rollout-restart
spec:
  params:
    - name: app-name
      type: string
    - name: namepace
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash
        echo "Rolling out deployment $(params.app-name)..."
        oc rollout restart deployment $(params.app-name) -n $(params.namespace)
        oc rollout status deployment $(params.app-name) -n $(params.namespace)
