kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: oc-rollout-restart
spec:
  params:
    - name: APP_NAME
      type: string
    - name: NAMESPACE
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash
        echo "Rolling out deployment $(params.APP_NAME)..."
        oc rollout restart deployment $(params.APP_NAME) -n $(params.NAMESPACE)
        oc rollout status deployment $(params.APP_NAME) -n $(params.NAMESPACE)
