apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/pittar-sandbox/gol-ui
  labels:
    app: gameoflife-ui
    app.kubernetes.io/component: gameoflife-ui
    app.kubernetes.io/instance: gameoflife-ui
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: gameoflife
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  name: gameoflife-ui
  namespace: gameoflife
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: gameoflife-ui:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/pittar-gameoflife/web-ui
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-11-el7
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
