kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: oc-binary-build
spec:
  workspaces:
    - name: build-workspace
      description: Build workspace.
  params:
    - name: build-name
      type: string
    - name: binary-relative-path
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      workingDir: $(workspaces.build-workspace.path)
      script: |
        #!/usr/bin/env bash
        echo "List target contents:"
        ls -l $(workspaces.build-workspace.path)/target
        oc start-build $(params.build-name) --from-file=$(workspaces.build-workspace.path)$(params.binary-relative-path) --follow