apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
  - name: source
  params:
  - name: GOALS
    description: The Maven goals to run, space spearated
    type: string
    default: "package"
  - name: PROFILES
    description: The Maven maven profiles to activate, comma separated
    type: string
    default: ""
  - name: ARGUMENTS
    description: Maven arguments, typically -D switches like -DskipTests
    type: string
    default: ""
  - name: MAVEN_MIRROR_URL
    description: The Maven bucketrepo- mirror
    type: string
    default: ""
  - name: MAVEN_REPO_CREDS_SECRET
    type: string
    description: name of the secret holding the maven repo credentials
    default: maven-repo-creds
  - name: M2_DIRECTORY
    type: string
    description: Location of M2 directory, do not change
    default: /root/.m2
  steps:
    - name: mvn-settings
      image: docker.io/maven:3.6.3-jdk-11
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          [[ -f $(params.M2_DIRECTORY)/settings.xml ]] && \
          echo 'using existing $(params.M2_DIRECTORY)/settings.xml' && \
          cat $(params.M2_DIRECTORY)/settings.xml && exit 0

          [[ -n '$(params.MAVEN_MIRROR_URL)' ]] && \
          cat > $(params.M2_DIRECTORY)/settings.xml <<EOF
          <settings>
            <mirrors>
              <mirror>
                <id>mirror.default</id>
                <name>mirror.default</name>
                <url>$(params.MAVEN_MIRROR_URL)</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>
          </settings>
          EOF

          [[ -f $(params.M2_DIRECTORY)/settings.xml ]] && cat $(params.M2_DIRECTORY)/settings.xml
          [[ -f $(params.M2_DIRECTORY)/settings.xml ]] || echo skipping settings
      volumeMounts:
        - name: m2-repository
          mountPath: $(params.M2_DIRECTORY)
        - name: maven-settings
          mountPath: $(params.M2_DIRECTORY)/settings.xml
          subPath: settings.xml
    - name: mvn-goals
      image: docker.io/maven:3.6.3-jdk-11
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          if [[ -z "$(params.PROFILES)" ]]; then
            mvn $(params.GOALS) $(params.ARGUMENTS)
          else
            mvn $(params.GOALS) -P$(params.PROFILES) $(params.ARGUMENTS)
          fi
      workingDir: $(workspaces.source.path)
      env:
        - name: MAVEN_SERVER_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.MAVEN_REPO_CREDS_SECRET)
              key: username
        - name: MAVEN_SERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.MAVEN_REPO_CREDS_SECRET)
              key: password
      volumeMounts:
        - name: m2-repository
          mountPath: $(params.M2_DIRECTORY)
        - name: maven-settings
          mountPath: $(params.M2_DIRECTORY)/settings.xml
          subPath: settings.xml
  volumes:
    - name: m2-repository
      persistentVolumeClaim:
        claimName: m2-cache
    - name: maven-settings
      configMap:
        name: maven-settings