kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: supervisor-build-and-rollout-init
spec:
  pipelineRef:
    name: supervisor-build-and-rollout
  params:
    - name: "git-url"
      value: "https://github.com/pittar-gameoflife/supervisor.git"
    - name: "git-revision"
      value: "master"
    - name: "app-name"
      value: "supervisor"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: supervisor-workspace
    - name: maven-settings-cm
      configMap:
        name: maven-settings-cm