apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: gameoflife-decisionmaker
    newName: quay.io/pittar/gameoflife-decisionmaker
    newTag: latest
  - name: gameoflife-supervisor
    newName: quay.io/pittar/gameoflife-supervisor
    newTag: latest
  - name: gameoflife-ui
    newName: quay.io/pittar/gameoflife-ui
    newTag: latest