apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources will be in dev-gameoflife namespace.
namespace: gameoflife-dev

# Gather common infrastructure and application resources.
bases:
  - ../../../base/02-environments
  - ../../../base/03-infrastructure
  - ../../../base/05-apps/01-decisions
  - ../../../base/05-apps/02-supervisor
  - ../../../base/05-apps/03-web-ui

# Include developer RoleBinding for the dev project.
resources:
  - 01-namespace.yaml
  - 02-developer-rolebinding.yaml

# Use the "dev" floating image tags.
images:
  - name: decisions
    newName: image-registry.openshift-image-registry.svc:5000/gameoflife-cicd/decisions-app
    newTag: dev
  - name: supervisor
    newName: image-registry.openshift-image-registry.svc:5000/gameoflife-cicd/supervisor-app
    newTag: dev
  - name: web-ui
    newName: image-registry.openshift-image-registry.svc:5000/gameoflife-cicd/web-ui-app
    newTag: dev
