kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: operators
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: openshift-operators
  source:
    path: overlays/01-operators
    repoURL: https://github.com/pittar-gameoflife/gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true