kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  name: gameoflife-cicd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: gameoflife-cicd
  source:
    path: overlays/02-environments/01-cicd
    repoURL: https://github.com/pittar-gameoflife/gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true